Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,4 +29,5 @@ jobs:
         run: |
           echo "Running ${{ github.event.inputs.test_type }} tests on ${{ github.event.inputs.environment }}"
           sleep 5
-          echo "Autotests finished successfully"
+          echo "Force test failure for log analysis" 
+          exit 1
